# Docker Compose to run app + PostgreSQL 
# .env.example: DATABASE_URL = "postgresql://tuan_phong:Phong2525132546879!@localhost:5432/be_assign"
version: '3.8'

services:
  web:
    build: .
    container_name: be_assign_web_container
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: be_assign_db_container
    restart: always
    environment:
      POSTGRES_DB: be_assign
      POSTGRES_USER: tuan_phong
      POSTGRES_PASSWORD: Phong2525132546879!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
