# Docker Compose to run app + PostgreSQL
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-01
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
