# Docker Compose to run app + PostgreSQL
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: be_assign_db_container
    restart: always
    environment:
      POSTGRES_DB: be_assign
      POSTGRES_USER: tuan_phong
      POSTGRES_PASSWORD: Phong2525132546879!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
